### ISSUE TITLE
Summary: Exceeds Expectations

### ISSUE THREAD

**Issue by surrealdetective** [softwaremom00/prj-rev-bwfs-dasmoto#5]
Your webpage looks identical to the mockup. Great work!

The HTML and CSS are formatted well:
- Spacing and indentation is correct, which makes it the project easy to read and work with 
- Use of alt in <img> so the webpage is more accessible
- Attention to detail in matching the mockup

Although what you have is already good, there are a few areas for improvement:
- Use a class over `<strong>`
- Use a font-family generic default

Keep up the good work!

**Comment by softwaremom00** [comment]
Thanks
